/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#faf8ff',
        'surface-bright': '#faf8ff',
        'surface-dim': '#d5d9eb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#e9edff',
        'surface-container-high': '#e4e7f9',
        'surface-container-highest': '#dee2f3',
        'surface-variant': '#dee2f3',
        'on-surface': '#161b28',
        'on-surface-variant': '#5d3f3c',
        'on-background': '#161b28',
        'background': '#faf8ff',

        'primary': '#d91023',
        'primary-dark': '#ad0017',
        'primary-container': '#d91023',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb3ad',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffecea',
        'on-primary-fixed': '#410003',
        'on-primary-fixed-variant': '#930011',
        'inverse-primary': '#ffb3ad',

        'secondary': '#203a7a',
        'secondary-container': '#4058b0',
        'secondary-fixed': '#dce1ff',
        'secondary-fixed-dim': '#b7c4ff',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#16338b',
        'on-secondary-fixed': '#001551',
        'on-secondary-fixed-variant': '#253f97',

        'tertiary': '#b8860b',
        'tertiary-container': '#8d6600',
        'tertiary-fixed': '#ffdea4',
        'tertiary-fixed-dim': '#fbbc2c',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffedd3',
        'on-tertiary-fixed': '#261900',
        'on-tertiary-fixed-variant': '#5d4200',

        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',

        'outline': '#926e6b',
        'outline-variant': '#e7bdb9',

        'inverse-surface': '#2b303d',
        'inverse-on-surface': '#edf0ff',
        'surface-tint': '#c0001a',

        'navy': '#0b1d3a',
        'navy-dark': '#071326',
        'idp-red': '#D91023',
        'idp-navy': '#1a2a6c',
        'idp-gold': '#EAA400',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'gutter': '1rem',
        'gutter-md': '1.5rem',
        'gutter-lg': '2rem',
        'margin': '1rem',
        'margin-md': '2rem',
        'margin-lg': '3rem',
      },
      fontFamily: {
        'headline-xl-mobile': ['Outfit'],
        'headline-xl': ['Outfit'],
        'headline-lg': ['Outfit'],
        'headline-lg-mobile': ['Outfit'],
        'headline-md': ['Outfit'],
        'headline-sm': ['Outfit'],
        'display-hero': ['Outfit'],
        'display-hero-mobile': ['Outfit'],
        'label-badge': ['Outfit'],
        'label-lg': ['Outfit'],
        'label-md': ['Outfit'],
        'label-sm': ['Outfit'],
        'body-lg': ['DM Sans'],
        'body-md': ['DM Sans'],
        'body-sm': ['DM Sans'],
        'score-display': ['Outfit'],
      },
      fontSize: {
        'headline-xl-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-xl': ['48px', { lineHeight: '54px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['36px', { lineHeight: '42px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '0em', fontWeight: '700' }],
        'headline-sm': ['20px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '600' }],
        'display-hero': ['48px', { lineHeight: '56px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'display-hero-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.025em', fontWeight: '800' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-lg': ['15px', { lineHeight: '20px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '0.06em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '700' }],
        'label-badge': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'score-display': ['28px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '800' }],
      },
      boxShadow: {
        '2xs': '0 1px 1px 0 rgb(0 0 0 / 0.05)',
        'xs': '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      },
    },
  },
  plugins: [],
}